#ifndef DEFINITION_H
#define DEFINITION_H

#define MINPROCCREDIT 16
#define MAXPROCCREDIT 35

#define MINCREDIT 1000000
#define MAXCREDIT 5000000

#define MINTIMECREDIT 1
#define MAXTIMECREDIT 5

#define MINPROCDEPOSIT 10
#define MAXPROCDEPOSIT 17

#define MINDEPOSIT 10000
#define MAXDEPOSIT 100000

#define MINTIMEDEPOSIT 1
#define MAXTIMEDEPOSIT 5

#endif // DEFINITION_H
